
namespace SGymManagerv2
{
    partial class frmInvoice
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmInvoice));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtReciept = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.cbbAppID = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label1 = new System.Windows.Forms.Label();
            this.txtMemID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtFirstname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLastname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtRegisterDate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.label8 = new System.Windows.Forms.Label();
            this.txtExpirationDate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.label9 = new System.Windows.Forms.Label();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label10 = new System.Windows.Forms.Label();
            this.txtCoursePrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.txtCoursename = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.txtCourseID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // txtReciept
            // 
            this.txtReciept.AcceptsReturn = false;
            this.txtReciept.AcceptsTab = false;
            this.txtReciept.AnimationSpeed = 100;
            this.txtReciept.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtReciept.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtReciept.BackColor = System.Drawing.Color.Transparent;
            this.txtReciept.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtReciept.BackgroundImage")));
            this.txtReciept.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtReciept.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtReciept.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtReciept.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtReciept.BorderRadius = 5;
            this.txtReciept.BorderThickness = 1;
            this.txtReciept.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtReciept.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtReciept.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtReciept.DefaultText = "";
            this.txtReciept.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtReciept.ForeColor = System.Drawing.Color.White;
            this.txtReciept.HideSelection = true;
            this.txtReciept.IconLeft = null;
            this.txtReciept.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtReciept.IconPadding = 10;
            this.txtReciept.IconRight = null;
            this.txtReciept.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtReciept.Lines = new string[0];
            this.txtReciept.Location = new System.Drawing.Point(137, 21);
            this.txtReciept.MaxLength = 32767;
            this.txtReciept.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtReciept.Modified = false;
            this.txtReciept.Multiline = false;
            this.txtReciept.Name = "txtReciept";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtReciept.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtReciept.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtReciept.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtReciept.OnIdleState = stateProperties4;
            this.txtReciept.Padding = new System.Windows.Forms.Padding(3);
            this.txtReciept.PasswordChar = '\0';
            this.txtReciept.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtReciept.PlaceholderText = "Reciept No";
            this.txtReciept.ReadOnly = false;
            this.txtReciept.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtReciept.SelectedText = "";
            this.txtReciept.SelectionLength = 0;
            this.txtReciept.SelectionStart = 0;
            this.txtReciept.ShortcutsEnabled = true;
            this.txtReciept.Size = new System.Drawing.Size(260, 41);
            this.txtReciept.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtReciept.TabIndex = 70;
            this.txtReciept.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtReciept.TextMarginBottom = 0;
            this.txtReciept.TextMarginLeft = 3;
            this.txtReciept.TextMarginTop = 0;
            this.txtReciept.TextPlaceholder = "Reciept No";
            this.txtReciept.UseSystemPasswordChar = false;
            this.txtReciept.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(37, 26);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(94, 28);
            this.label2.TabIndex = 71;
            this.label2.Text = "Invoice ID";
            // 
            // cbbAppID
            // 
            this.cbbAppID.BackColor = System.Drawing.Color.Transparent;
            this.cbbAppID.BackgroundColor = System.Drawing.Color.Transparent;
            this.cbbAppID.BorderColor = System.Drawing.Color.Silver;
            this.cbbAppID.BorderRadius = 5;
            this.cbbAppID.Color = System.Drawing.Color.Silver;
            this.cbbAppID.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbAppID.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbAppID.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbAppID.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbAppID.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbAppID.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbAppID.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbAppID.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbAppID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbAppID.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbAppID.FillDropDown = true;
            this.cbbAppID.FillIndicator = false;
            this.cbbAppID.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbAppID.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbAppID.ForeColor = System.Drawing.Color.White;
            this.cbbAppID.FormattingEnabled = true;
            this.cbbAppID.Icon = null;
            this.cbbAppID.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbAppID.IndicatorColor = System.Drawing.Color.Gray;
            this.cbbAppID.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbAppID.ItemBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.cbbAppID.ItemBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.cbbAppID.ItemForeColor = System.Drawing.Color.White;
            this.cbbAppID.ItemHeight = 24;
            this.cbbAppID.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(156)))), ((int)(((byte)(18)))));
            this.cbbAppID.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbAppID.ItemTopMargin = 3;
            this.cbbAppID.Location = new System.Drawing.Point(534, 24);
            this.cbbAppID.Name = "cbbAppID";
            this.cbbAppID.Size = new System.Drawing.Size(260, 30);
            this.cbbAppID.TabIndex = 73;
            this.cbbAppID.Text = null;
            this.cbbAppID.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbAppID.TextLeftMargin = 5;
            this.cbbAppID.SelectedIndexChanged += new System.EventHandler(this.cbbAppID_SelectedIndexChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label1.ForeColor = System.Drawing.SystemColors.Window;
            this.label1.Location = new System.Drawing.Point(445, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(83, 28);
            this.label1.TabIndex = 72;
            this.label1.Text = "Apply ID";
            // 
            // txtMemID
            // 
            this.txtMemID.AcceptsReturn = false;
            this.txtMemID.AcceptsTab = false;
            this.txtMemID.AnimationSpeed = 100;
            this.txtMemID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMemID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMemID.BackColor = System.Drawing.Color.Transparent;
            this.txtMemID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMemID.BackgroundImage")));
            this.txtMemID.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtMemID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMemID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtMemID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMemID.BorderRadius = 5;
            this.txtMemID.BorderThickness = 1;
            this.txtMemID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMemID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMemID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMemID.DefaultText = "";
            this.txtMemID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtMemID.ForeColor = System.Drawing.Color.White;
            this.txtMemID.HideSelection = true;
            this.txtMemID.IconLeft = null;
            this.txtMemID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMemID.IconPadding = 10;
            this.txtMemID.IconRight = null;
            this.txtMemID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMemID.Lines = new string[0];
            this.txtMemID.Location = new System.Drawing.Point(939, 21);
            this.txtMemID.MaxLength = 32767;
            this.txtMemID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMemID.Modified = false;
            this.txtMemID.Multiline = false;
            this.txtMemID.Name = "txtMemID";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMemID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMemID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMemID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMemID.OnIdleState = stateProperties8;
            this.txtMemID.Padding = new System.Windows.Forms.Padding(3);
            this.txtMemID.PasswordChar = '\0';
            this.txtMemID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMemID.PlaceholderText = "ID";
            this.txtMemID.ReadOnly = true;
            this.txtMemID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMemID.SelectedText = "";
            this.txtMemID.SelectionLength = 0;
            this.txtMemID.SelectionStart = 0;
            this.txtMemID.ShortcutsEnabled = true;
            this.txtMemID.Size = new System.Drawing.Size(260, 41);
            this.txtMemID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMemID.TabIndex = 74;
            this.txtMemID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMemID.TextMarginBottom = 0;
            this.txtMemID.TextMarginLeft = 3;
            this.txtMemID.TextMarginTop = 0;
            this.txtMemID.TextPlaceholder = "ID";
            this.txtMemID.UseSystemPasswordChar = false;
            this.txtMemID.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(813, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(106, 28);
            this.label3.TabIndex = 75;
            this.label3.Text = "Member ID";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(62, 93);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(62, 28);
            this.label4.TabIndex = 77;
            this.label4.Text = "Name";
            // 
            // txtFirstname
            // 
            this.txtFirstname.AcceptsReturn = false;
            this.txtFirstname.AcceptsTab = false;
            this.txtFirstname.AnimationSpeed = 100;
            this.txtFirstname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFirstname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFirstname.BackColor = System.Drawing.Color.Transparent;
            this.txtFirstname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFirstname.BackgroundImage")));
            this.txtFirstname.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtFirstname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFirstname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtFirstname.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFirstname.BorderRadius = 5;
            this.txtFirstname.BorderThickness = 1;
            this.txtFirstname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFirstname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtFirstname.DefaultText = "";
            this.txtFirstname.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtFirstname.ForeColor = System.Drawing.Color.White;
            this.txtFirstname.HideSelection = true;
            this.txtFirstname.IconLeft = null;
            this.txtFirstname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstname.IconPadding = 10;
            this.txtFirstname.IconRight = null;
            this.txtFirstname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstname.Lines = new string[0];
            this.txtFirstname.Location = new System.Drawing.Point(137, 87);
            this.txtFirstname.MaxLength = 32767;
            this.txtFirstname.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFirstname.Modified = false;
            this.txtFirstname.Multiline = false;
            this.txtFirstname.Name = "txtFirstname";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstname.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFirstname.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstname.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstname.OnIdleState = stateProperties12;
            this.txtFirstname.Padding = new System.Windows.Forms.Padding(3);
            this.txtFirstname.PasswordChar = '\0';
            this.txtFirstname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFirstname.PlaceholderText = "Firstname";
            this.txtFirstname.ReadOnly = true;
            this.txtFirstname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFirstname.SelectedText = "";
            this.txtFirstname.SelectionLength = 0;
            this.txtFirstname.SelectionStart = 0;
            this.txtFirstname.ShortcutsEnabled = true;
            this.txtFirstname.Size = new System.Drawing.Size(260, 41);
            this.txtFirstname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFirstname.TabIndex = 76;
            this.txtFirstname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFirstname.TextMarginBottom = 0;
            this.txtFirstname.TextMarginLeft = 3;
            this.txtFirstname.TextMarginTop = 0;
            this.txtFirstname.TextPlaceholder = "Firstname";
            this.txtFirstname.UseSystemPasswordChar = false;
            this.txtFirstname.WordWrap = true;
            // 
            // txtLastname
            // 
            this.txtLastname.AcceptsReturn = false;
            this.txtLastname.AcceptsTab = false;
            this.txtLastname.AnimationSpeed = 100;
            this.txtLastname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLastname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLastname.BackColor = System.Drawing.Color.Transparent;
            this.txtLastname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLastname.BackgroundImage")));
            this.txtLastname.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtLastname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLastname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtLastname.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLastname.BorderRadius = 5;
            this.txtLastname.BorderThickness = 1;
            this.txtLastname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLastname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLastname.DefaultText = "";
            this.txtLastname.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtLastname.ForeColor = System.Drawing.Color.White;
            this.txtLastname.HideSelection = true;
            this.txtLastname.IconLeft = null;
            this.txtLastname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastname.IconPadding = 10;
            this.txtLastname.IconRight = null;
            this.txtLastname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastname.Lines = new string[0];
            this.txtLastname.Location = new System.Drawing.Point(534, 87);
            this.txtLastname.MaxLength = 32767;
            this.txtLastname.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLastname.Modified = false;
            this.txtLastname.Multiline = false;
            this.txtLastname.Name = "txtLastname";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastname.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLastname.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastname.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastname.OnIdleState = stateProperties16;
            this.txtLastname.Padding = new System.Windows.Forms.Padding(3);
            this.txtLastname.PasswordChar = '\0';
            this.txtLastname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLastname.PlaceholderText = "Lastname";
            this.txtLastname.ReadOnly = true;
            this.txtLastname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLastname.SelectedText = "";
            this.txtLastname.SelectionLength = 0;
            this.txtLastname.SelectionStart = 0;
            this.txtLastname.ShortcutsEnabled = true;
            this.txtLastname.Size = new System.Drawing.Size(260, 41);
            this.txtLastname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLastname.TabIndex = 78;
            this.txtLastname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLastname.TextMarginBottom = 0;
            this.txtLastname.TextMarginLeft = 3;
            this.txtLastname.TextMarginTop = 0;
            this.txtLastname.TextPlaceholder = "Lastname";
            this.txtLastname.UseSystemPasswordChar = false;
            this.txtLastname.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(436, 93);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(92, 28);
            this.label5.TabIndex = 79;
            this.label5.Text = "Lastname";
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 100;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhone.BorderRadius = 5;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtPhone.ForeColor = System.Drawing.Color.White;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(939, 87);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties20;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "Phone Number";
            this.txtPhone.ReadOnly = true;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(260, 41);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 80;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 0;
            this.txtPhone.TextPlaceholder = "Phone Number";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(813, 93);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(107, 28);
            this.label6.TabIndex = 81;
            this.label6.Text = "Tel Number";
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.AnimationSpeed = 100;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddress.BorderRadius = 5;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtAddress.ForeColor = System.Drawing.Color.White;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(137, 144);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = false;
            this.txtAddress.Name = "txtAddress";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties24;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "Address";
            this.txtAddress.ReadOnly = true;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(657, 96);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddress.TabIndex = 83;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 3;
            this.txtAddress.TextMarginTop = -20;
            this.txtAddress.TextPlaceholder = "Address";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(51, 147);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(80, 28);
            this.label7.TabIndex = 82;
            this.label7.Text = "Address";
            // 
            // txtRegisterDate
            // 
            this.txtRegisterDate.BackColor = System.Drawing.Color.Transparent;
            this.txtRegisterDate.BorderRadius = 5;
            this.txtRegisterDate.CalendarMonthBackground = System.Drawing.Color.Transparent;
            this.txtRegisterDate.Color = System.Drawing.Color.Silver;
            this.txtRegisterDate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.txtRegisterDate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.txtRegisterDate.DisabledColor = System.Drawing.Color.Gray;
            this.txtRegisterDate.DisplayWeekNumbers = false;
            this.txtRegisterDate.DPHeight = 0;
            this.txtRegisterDate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.txtRegisterDate.FillDatePicker = false;
            this.txtRegisterDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtRegisterDate.ForeColor = System.Drawing.Color.White;
            this.txtRegisterDate.Icon = ((System.Drawing.Image)(resources.GetObject("txtRegisterDate.Icon")));
            this.txtRegisterDate.IconColor = System.Drawing.Color.White;
            this.txtRegisterDate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.txtRegisterDate.LeftTextMargin = 5;
            this.txtRegisterDate.Location = new System.Drawing.Point(943, 147);
            this.txtRegisterDate.MinimumSize = new System.Drawing.Size(4, 32);
            this.txtRegisterDate.Name = "txtRegisterDate";
            this.txtRegisterDate.Size = new System.Drawing.Size(256, 32);
            this.txtRegisterDate.TabIndex = 94;
            this.txtRegisterDate.Value = new System.DateTime(2021, 3, 11, 16, 17, 0, 0);
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(840, 147);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(79, 28);
            this.label8.TabIndex = 93;
            this.label8.Text = "Register";
            // 
            // txtExpirationDate
            // 
            this.txtExpirationDate.BackColor = System.Drawing.Color.Transparent;
            this.txtExpirationDate.BorderRadius = 5;
            this.txtExpirationDate.CalendarMonthBackground = System.Drawing.Color.Transparent;
            this.txtExpirationDate.Color = System.Drawing.Color.Silver;
            this.txtExpirationDate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.txtExpirationDate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.txtExpirationDate.DisabledColor = System.Drawing.Color.Gray;
            this.txtExpirationDate.DisplayWeekNumbers = false;
            this.txtExpirationDate.DPHeight = 0;
            this.txtExpirationDate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.txtExpirationDate.FillDatePicker = false;
            this.txtExpirationDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtExpirationDate.ForeColor = System.Drawing.Color.White;
            this.txtExpirationDate.Icon = ((System.Drawing.Image)(resources.GetObject("txtExpirationDate.Icon")));
            this.txtExpirationDate.IconColor = System.Drawing.Color.White;
            this.txtExpirationDate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.txtExpirationDate.LeftTextMargin = 5;
            this.txtExpirationDate.Location = new System.Drawing.Point(943, 208);
            this.txtExpirationDate.MinimumSize = new System.Drawing.Size(4, 32);
            this.txtExpirationDate.Name = "txtExpirationDate";
            this.txtExpirationDate.Size = new System.Drawing.Size(256, 32);
            this.txtExpirationDate.TabIndex = 96;
            this.txtExpirationDate.Value = new System.DateTime(2021, 3, 11, 16, 17, 0, 0);
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(825, 208);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(94, 28);
            this.label9.TabIndex = 95;
            this.label9.Text = "Expiration";
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges1;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 10;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.IdleBorderRadius = 5;
            this.btnDelete.IdleBorderThickness = 1;
            this.btnDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.IdleIconLeftImage = null;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(658, 337);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 5;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.onHoverState.BorderRadius = 5;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.OnIdleState.BorderRadius = 5;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnIdleState.IconLeftImage = null;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.OnPressedState.BorderRadius = 5;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(136, 39);
            this.btnDelete.TabIndex = 100;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges2;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.IdleBorderRadius = 5;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(473, 337);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 5;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.onHoverState.BorderRadius = 5;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.OnIdleState.BorderRadius = 5;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.OnPressedState.BorderRadius = 5;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(136, 39);
            this.btnSave.TabIndex = 98;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(880, 262);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(53, 28);
            this.label10.TabIndex = 106;
            this.label10.Text = "Price";
            // 
            // txtCoursePrice
            // 
            this.txtCoursePrice.AcceptsReturn = false;
            this.txtCoursePrice.AcceptsTab = false;
            this.txtCoursePrice.AnimationSpeed = 100;
            this.txtCoursePrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCoursePrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCoursePrice.BackColor = System.Drawing.Color.Transparent;
            this.txtCoursePrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCoursePrice.BackgroundImage")));
            this.txtCoursePrice.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtCoursePrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCoursePrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtCoursePrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCoursePrice.BorderRadius = 5;
            this.txtCoursePrice.BorderThickness = 1;
            this.txtCoursePrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCoursePrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursePrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCoursePrice.DefaultText = "";
            this.txtCoursePrice.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtCoursePrice.ForeColor = System.Drawing.Color.White;
            this.txtCoursePrice.HideSelection = true;
            this.txtCoursePrice.IconLeft = null;
            this.txtCoursePrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursePrice.IconPadding = 10;
            this.txtCoursePrice.IconRight = null;
            this.txtCoursePrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursePrice.Lines = new string[0];
            this.txtCoursePrice.Location = new System.Drawing.Point(939, 256);
            this.txtCoursePrice.MaxLength = 32767;
            this.txtCoursePrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCoursePrice.Modified = false;
            this.txtCoursePrice.Multiline = false;
            this.txtCoursePrice.Name = "txtCoursePrice";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursePrice.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCoursePrice.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursePrice.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursePrice.OnIdleState = stateProperties28;
            this.txtCoursePrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtCoursePrice.PasswordChar = '\0';
            this.txtCoursePrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCoursePrice.PlaceholderText = "Price";
            this.txtCoursePrice.ReadOnly = true;
            this.txtCoursePrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCoursePrice.SelectedText = "";
            this.txtCoursePrice.SelectionLength = 0;
            this.txtCoursePrice.SelectionStart = 0;
            this.txtCoursePrice.ShortcutsEnabled = true;
            this.txtCoursePrice.Size = new System.Drawing.Size(260, 41);
            this.txtCoursePrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCoursePrice.TabIndex = 105;
            this.txtCoursePrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCoursePrice.TextMarginBottom = 0;
            this.txtCoursePrice.TextMarginLeft = 3;
            this.txtCoursePrice.TextMarginTop = 0;
            this.txtCoursePrice.TextPlaceholder = "Price";
            this.txtCoursePrice.UseSystemPasswordChar = false;
            this.txtCoursePrice.WordWrap = true;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(332, 262);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(126, 28);
            this.label11.TabIndex = 104;
            this.label11.Text = "Course Name";
            // 
            // txtCoursename
            // 
            this.txtCoursename.AcceptsReturn = false;
            this.txtCoursename.AcceptsTab = false;
            this.txtCoursename.AnimationSpeed = 100;
            this.txtCoursename.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCoursename.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCoursename.BackColor = System.Drawing.Color.Transparent;
            this.txtCoursename.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCoursename.BackgroundImage")));
            this.txtCoursename.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtCoursename.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCoursename.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtCoursename.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCoursename.BorderRadius = 5;
            this.txtCoursename.BorderThickness = 1;
            this.txtCoursename.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCoursename.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursename.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCoursename.DefaultText = "";
            this.txtCoursename.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtCoursename.ForeColor = System.Drawing.Color.White;
            this.txtCoursename.HideSelection = true;
            this.txtCoursename.IconLeft = null;
            this.txtCoursename.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursename.IconPadding = 10;
            this.txtCoursename.IconRight = null;
            this.txtCoursename.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCoursename.Lines = new string[0];
            this.txtCoursename.Location = new System.Drawing.Point(473, 256);
            this.txtCoursename.MaxLength = 32767;
            this.txtCoursename.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCoursename.Modified = false;
            this.txtCoursename.Multiline = false;
            this.txtCoursename.Name = "txtCoursename";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursename.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCoursename.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursename.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCoursename.OnIdleState = stateProperties32;
            this.txtCoursename.Padding = new System.Windows.Forms.Padding(3);
            this.txtCoursename.PasswordChar = '\0';
            this.txtCoursename.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCoursename.PlaceholderText = "Course Name";
            this.txtCoursename.ReadOnly = true;
            this.txtCoursename.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCoursename.SelectedText = "";
            this.txtCoursename.SelectionLength = 0;
            this.txtCoursename.SelectionStart = 0;
            this.txtCoursename.ShortcutsEnabled = true;
            this.txtCoursename.Size = new System.Drawing.Size(401, 41);
            this.txtCoursename.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCoursename.TabIndex = 103;
            this.txtCoursename.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCoursename.TextMarginBottom = 0;
            this.txtCoursename.TextMarginLeft = 3;
            this.txtCoursename.TextMarginTop = 0;
            this.txtCoursename.TextPlaceholder = "Course Name";
            this.txtCoursename.UseSystemPasswordChar = false;
            this.txtCoursename.WordWrap = true;
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI Light", 12F);
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(37, 261);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(94, 28);
            this.label12.TabIndex = 102;
            this.label12.Text = "Course ID";
            // 
            // txtCourseID
            // 
            this.txtCourseID.AcceptsReturn = false;
            this.txtCourseID.AcceptsTab = false;
            this.txtCourseID.AnimationSpeed = 100;
            this.txtCourseID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCourseID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCourseID.BackColor = System.Drawing.Color.Transparent;
            this.txtCourseID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCourseID.BackgroundImage")));
            this.txtCourseID.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.txtCourseID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCourseID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.txtCourseID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCourseID.BorderRadius = 5;
            this.txtCourseID.BorderThickness = 1;
            this.txtCourseID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCourseID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCourseID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCourseID.DefaultText = "";
            this.txtCourseID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.txtCourseID.ForeColor = System.Drawing.Color.White;
            this.txtCourseID.HideSelection = true;
            this.txtCourseID.IconLeft = null;
            this.txtCourseID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCourseID.IconPadding = 10;
            this.txtCourseID.IconRight = null;
            this.txtCourseID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCourseID.Lines = new string[0];
            this.txtCourseID.Location = new System.Drawing.Point(137, 256);
            this.txtCourseID.MaxLength = 32767;
            this.txtCourseID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCourseID.Modified = false;
            this.txtCourseID.Multiline = false;
            this.txtCourseID.Name = "txtCourseID";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCourseID.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCourseID.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCourseID.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCourseID.OnIdleState = stateProperties36;
            this.txtCourseID.Padding = new System.Windows.Forms.Padding(3);
            this.txtCourseID.PasswordChar = '\0';
            this.txtCourseID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCourseID.PlaceholderText = "Course ID";
            this.txtCourseID.ReadOnly = true;
            this.txtCourseID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCourseID.SelectedText = "";
            this.txtCourseID.SelectionLength = 0;
            this.txtCourseID.SelectionStart = 0;
            this.txtCourseID.ShortcutsEnabled = true;
            this.txtCourseID.Size = new System.Drawing.Size(189, 41);
            this.txtCourseID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCourseID.TabIndex = 101;
            this.txtCourseID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCourseID.TextMarginBottom = 0;
            this.txtCourseID.TextMarginLeft = 3;
            this.txtCourseID.TextMarginTop = 0;
            this.txtCourseID.TextPlaceholder = "Course ID";
            this.txtCourseID.UseSystemPasswordChar = false;
            this.txtCourseID.WordWrap = true;
            // 
            // frmInvoice
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.ClientSize = new System.Drawing.Size(1288, 606);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.txtCoursePrice);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.txtCoursename);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.txtCourseID);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtExpirationDate);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.txtRegisterDate);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.txtAddress);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtPhone);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txtLastname);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtFirstname);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtMemID);
            this.Controls.Add(this.cbbAppID);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txtReciept);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmInvoice";
            this.Text = "frmInvoice";
            this.Load += new System.EventHandler(this.frmInvoice_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtReciept;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuDropdown cbbAppID;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtMemID;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtFirstname;
        private Bunifu.UI.WinForms.BunifuTextBox txtLastname;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddress;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuDatePicker txtRegisterDate;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuDatePicker txtExpirationDate;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private System.Windows.Forms.Label label10;
        private Bunifu.UI.WinForms.BunifuTextBox txtCoursePrice;
        private System.Windows.Forms.Label label11;
        private Bunifu.UI.WinForms.BunifuTextBox txtCoursename;
        private System.Windows.Forms.Label label12;
        private Bunifu.UI.WinForms.BunifuTextBox txtCourseID;
    }
}